### ISSUE TITLE
MMCE-weighted results

### ISSUE THREAD

**Issue by paganpasta** [torrvision/focal_calibration#12]
Hi,

I observed that the MMCE_w's results are consistently worse than the baseline. Whereas, the MMCE authors report better ECE results on CIFAR-10/100 in their paper. Any idea as to why it performs worse?   

Thanks.

**Comment by vivkul** [comment]
Hi,

We haven't done early stopping based on any calibration metric (like ECE) as there is a trade-off between ECE and accuracy. Doing early stopping based on ECE may provide better results and the MMCE authors seem to have done that.
