### ISSUE TITLE
model and dataloader files for 20 newsgroup dataset

### ISSUE THREAD

**Issue by bicycleman15** [torrvision/focal_calibration#15]
I cannot find anywhere the files to train for the 20 newsgroup dataset.
you have provided the trained models on focal loss but no way to load those models since there is no model file in `Net` directory. Similarly no dataloader for 20 newsgroup dataset in `Data` directory.

Could you please release those as well ?

**Comment by vivkul** [comment]
Hello,

Thanks for considering our code. We just put the code for the nlp experiments in the [nlp branch](https://github.com/torrvision/focal_calibration/tree/nlp).
For installations, you may have to refer the referenced repos in the [README](https://github.com/torrvision/focal_calibration/blob/nlp/README.md).

Please reachout if you face any issue. Thanks!

**Comment by omegafragger** [comment]
Thanks Viveka for the quick resolution and maintenance of the repo! Really
appreciate it!
