### ISSUE TITLE
In paper there is no where mentioned that when p_t >= 0.5, we should set \gamma to 0.

### ISSUE THREAD

**Issue by circlecrystal** [torrvision/focal_calibration#6]
https://github.com/torrvision/focal_calibration/blob/04a0e9e098dad3a5c59f11242a9fd01635d284e0/Losses/focal_loss_adaptive_gamma.py#L45

In paper there is no where mentioned that when p_t >= 0.5, we should set \gamma to 0.
Is there any mistake in the code?

**Comment by vivkul** [comment]
Hi, FocalLossAdaptive is initialized using https://github.com/torrvision/focal_calibration/blob/04a0e9e098dad3a5c59f11242a9fd01635d284e0/train_utils.py#L50 . Here, the argument provided for 'FocalLossAdaptive' can either be gamma=3 (same as FLSD-53 in the main paper) or gamma=2 (same as FLSD-532 in the appendix). 
I hope it clarifies.

**Comment by vivkul** [comment]
The scripts to train different models is now available here: https://github.com/torrvision/focal_calibration/tree/main/train_scripts
